services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  CommerceGuys\Intl\NumberFormat\NumberFormatRepository: ~

  Shopsys\FrameworkBundle\Component\Localization\DateTimeFormatter:
    factory: ['@Shopsys\FrameworkBundle\Model\Localization\CustomDateTimeFormatterFactory', create]

  Shopsys\FrameworkBundle\Model\Localization\IntlCurrencyRepository: ~

  Shopsys\FrameworkBundle\Model\Newsletter\NewsletterFacade: ~

  Shopsys\FrameworkBundle\Model\Localization\TranslatableListener: ~
